version: '3'
services:
  twitter-web:
    # build: .
    image: twitter-web:v1.0.2
    # volumes:
    #   - ./:/usr/src/app
    environment:
      - "REACT_APP_API_HOST=hoge"
    command: sh -c "npm start"
    ports:
      - "3000:3000"